# Configuration d'exemple pour CachyRust
# Copiez ce fichier vers ~/.config/cachy-rust/config.toml et modifiez selon vos besoins

[scheduler]
# Activer les mises à jour automatiques
enabled = false
# Heure de mise à jour (format HH:MM)
update_time = "08:00"
# Fuseau horaire
timezone = "Europe/Paris"

[telegram]
# Activer les notifications Telegram
enabled = false
# Token du bot Telegram (obtenez-le via @BotFather)
bot_token = ""
# ID du chat Telegram (obtenez-le via @userinfobot)
chat_id = ""
# Envoyer les notifications de succès
send_success = true
# Envoyer les notifications d'erreur
send_errors = true

[system]
# Redémarrage automatique si requis par les mises à jour
auto_reboot = false
# Délai avant redémarrage (en minutes)
reboot_delay_minutes = 5
# Créer une sauvegarde avant mise à jour
backup_before_update = true
# Nombre maximum d'entrées dans l'historique
max_history_entries = 100

[gui]
# Thème de l'interface ("light", "dark", "auto")
theme = "auto"
# Largeur de la fenêtre
window_width = 800
# Hauteur de la fenêtre
window_height = 600
# Minimiser dans la barre système
minimize_to_tray = true